version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luxspace
    container_name: luxspace-laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: luxspace-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: luxspace
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql